realsense_static_transform_publisher:
  ros__parameters:
    x: '0.43'
    y: '0.0'
    z: '0.56' 
    #  incoming left imager test 0.25896 0.015977 0.568176

    # roll: '-2.29133009' # this affects camera pitch
    # pitch: '-0.045' # this affects camera roll
    roll: '0.0' # this affects camera pitch
    pitch: '0.5236' # this affects camera roll
    yaw: '0.0'
    parent_frame_id: 'base_link'
    child_frame_id: 'camera_link'

    
