behavior_executive_node:
  ros__parameters:
    # Timer callbacks
    fsm_timer_callback_ms: 500 # milliseconds
    service_response_timeout_ms: 500 # milliseconds
    viz_timer_callback_ms: 500 # milliseconds

    # Map parameters
    height: 70 # number of cells in col
    width: 70 # number cells in row
    resolution: 0.1 # meters

    # Callback-group syncronous
    sync_callback_groups: true # MUST BE TRUE TO AVOID RUNTIME MEMORY COLLISIONS!!! MAKE FALSE ONLY ONLY ONLY FOR DEBUG!!!