zed_static_transform_publisher:
  ros__parameters:
    x: 1.0
    y: 0.0
    z: 0.5
    yaw: 0.0
    pitch: -1.57079632679
    roll: 0.0
    parent_frame_id: base_link
    child_frame_id: zed_camera_link