#include "std_msgs/msg/Header.idl"

module lr_msgs {
  module msg {
    struct BeaconMultiTag {
      std_msgs::msg::Header header;

      // Array of Tag info (currently expecting only 2 at most)
      lr_msgs::msg::BeaconTag TagsList [2];

    };
  };
};
