# GOAL: The path to follow
nav_msgs/Path path
---
# RESULT: Did the robot successfully reach the goal?
bool success
---
# FEEDBACK: The robot's current distance to the final goal
float32 distance_to_goal