behavior_executive_node:
  ros__parameters:
    # Timer callbacks
    fsm_timer_callback_ms: 500 # milliseconds
    service_response_timeout_ms: 500 # milliseconds
    viz_timer_callback_ms: 500 # milliseconds

    # Map parameters
    height: 70 # number of cells in col
    width: 70 # number cells in row
    resolution: 0.1 # meters

    # Transport planner
    source_threshold_z: 0.03 # meters off fit plane
    sink_threshold_z: 0.01 # meters below fit plane
    thresh_max_assignment_distance: 0.4 # max meters between transport assignments
    last_pose_offset: 1.0 # meters to rearward offset last pose in transport assignment by
    source_pose_offset: 0.3 # meters to rearward offset source pose in transport assignment by
    transport_plan_max_calls: 100 # Number of calls to REPLAN_TRANSPORT before a replan is triggered
    boundary_min: 0.7 # max pose for x-y in sitemap frame
    boundary_max: 4.3 # min pose for x-y in sitemap frame
    thresh_filter_assignment_pos: 1.0 # minimum meters between final transport assignments
    thresh_filter_assignment_head: 6.28 # minimum heading [rad] between final transport assignments

    # Map loading
    # design_topo_filepath: "/root/Lunar_ROADSTER/lr_ws/src/planning/saved_maps/zeros_height_map.csv" # use absolute path
    # site_topo_filepath: "/root/Lunar_ROADSTER/lr_ws/src/planning/saved_maps/elevation_map_1d.csv" # use absolute path
    current_map_file: /home/williamfbx/Lunar-ROADSTER/lr_ws/src/planning/saved_maps/elevation_map_1d.csv 
    design_map_file: /home/williamfbx/Lunar-ROADSTER/lr_ws/src/planning/saved_maps/zeros_height_map.csv

    # Callback-group syncronous
    sync_callback_groups: true # MUST BE TRUE TO AVOID RUNTIME MEMORY COLLISIONS!!! MAKE FALSE ONLY ONLY ONLY FOR DEBUG!!!