local_controller_node:
  ros__parameters:
    max_linear_velocity: 
    max_angular_velocity: 
    yaw_threshold: 
    window_duration: 
    goal_tolerance: 
    yaw_tolerance: 

    Q_pos: 150
    Q_yaw: 300
    R: 1

    radius: 2.0
    dt: 0.1
    horizon: 20

    use_mpc: true
    
    goal_offset_x: 
    goal_offset_y: 
    goal_offset_yaw: 
    goal_stable_threshold: 
